group:
  repos: |
    revoltchat/revite
    revoltchat/frontend
    revoltchat/android
    revoltchat/revolt
    revoltchat/backend
    revoltchat/vortex
    revoltchat/autumn
    revoltchat/january
    revoltchat/revolt.js
    revoltchat/api
    revoltchat/translations
    revoltchat/themes
    revoltchat/desktop
    revoltchat/android-twa
    revoltchat/lists_vpn
    revoltchat/documentation
    revoltchat/genemoji
    revoltchat/self-hosted
    revoltchat/legal
    revoltchat/contributions
    revoltchat/fdroid
    revoltchat/revolt.chat
  files:
    - source: workflows/triage_issue.yml
      dest: .github/workflows/triage_issue.yml
    - source: workflows/triage_pr.yml
      dest: .github/workflows/triage_pr.yml
