group:
  repos: |
    revoltchat/android-twa
    revoltchat/api
    revoltchat/autumn
    revoltchat/bonfire
    revoltchat/cli
    revoltchat/delta
    revoltchat/desktop
    revoltchat/fdroid
    revoltchat/january
    revoltchat/legal
    revoltchat/quark
    revoltchat/revite
    revoltchat/revolt
    revoltchat/revolt.chat
    revoltchat/revolt.js
    revoltchat/self-hosted
    revoltchat/themes
    revoltchat/translations
    revoltchat/vortex
  files:
    - source: workflows/triage_issue.yml
      dest: .github/workflows/triage_issue.yml
    - source: workflows/triage_pr.yml
      dest: .github/workflows/triage_pr.yml
